# Generated by Django 5.2.5 on 2025-09-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('canvas', 'Canvas'), ('shoot', 'Shoot')], default='canvas', max_length=20)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('updated_day', models.DateTimeField(auto_now=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='canvas.canvas')),
            ],
            options={
                'db_table': 'feedbacksessions',
            },
        ),
    ]
