# Generated by Django 5.2.5 on 2025-09-23 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacksessions', '0001_initial'),
        ('users', '0002_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sessions', to='users.user'),
        ),
    ]
