# Generated by Django 5.2.5 on 2025-09-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacksessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('tag_user', models.IntegerField(blank=True, null=True)),
                ('mention_user', models.JSONField(blank=True, null=True)),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedbacksessions.feedbacksession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
