# Generated by Django 5.2.5 on 2025-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
