# Generated by Django 5.2.5 on 2025-09-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_position_x_comment_position_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
