# Generated by Django 5.2.5 on 2025-09-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.TextField()),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model', models.CharField(choices=[('project', 'Project'), ('comment', 'Comment'), ('user', 'User')], max_length=20)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
    ]
