# Generated by Django 5.2.5 on 2025-09-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('auth_type', models.CharField(choices=[('default', 'Default'), ('google', 'Google'), ('sso', 'SSO')], default='default', max_length=20)),
                ('two_stept_auth', models.BooleanField(default=False)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
