# Generated by Django 5.2.5 on 2025-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
